<a href="https://colab.research.google.com/github/JahnaviSatishShanbhag/codeio_python_course/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [6]:
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
a.shape

(3, 5)

In [8]:
a.ndim

2

In [9]:
a.dtype.name

'int64'

In [10]:
a.itemsize

8

In [11]:
a.size

15

In [12]:
type(a)

numpy.ndarray

In [13]:
a = np.array([2, 3, 4])
a 

array([2, 3, 4])

In [14]:
a.dtype 

dtype('int64')

In [15]:
b = np.array([1.2, 3.5, 5.1])
b.dtype 

dtype('float64')

In [16]:
b= np.array([(1, 2, 3, 4) ,(5, 6, 7, 8)])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
c = np.array([[1, 2] , [3, 4]] , dtype = complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [20]:
np.empty((2,3))

array([[4.63876356e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [22]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [24]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [27]:
from numpy import pi
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [29]:
x = np.linspace(0, 2*pi, 100)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [31]:
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [33]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a -b 
c

array([20, 29, 38, 47])

In [35]:
A = np.array([[1, 1],[0, 1]])
B = np.array([[2, 0],[3, 4]])

In [36]:
A*B

array([[2, 0],
       [0, 4]])

In [37]:
A@B

array([[5, 4],
       [3, 4]])

In [38]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [44]:
rg = np.random.default_rng(1)
rg

Generator(PCG64) at 0x7FEAE1D2B150

In [41]:
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [46]:
b += a
b
#a += b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [47]:
B = np.arange(3)
B

array([0, 1, 2])

In [48]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [49]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [50]:
C = np.array([2., -1., 4.])
np.add(B, C) 

array([2., 0., 6.])

In [52]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [53]:
a[2]

8

In [54]:
a[2 : 5] 

array([ 8, 27, 64])

In [56]:
a[ : 6 : 2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])